### ISSUE TITLE
un-authed flow

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#133] opened 2023-01-19 21:27 UTC
# story
unauthorized users can still access the home and browse pages (client credential flow)
we will need to work with a supplier access token

# related
#68 auth epic
https://github.com/scientist-softserv/webstore/issues/132 authed flow

**Comment by alishaevn** [comment] 2023-01-19 22:59
this is a duplicate of https://github.com/scientist-softserv/webstore/issues/67.

**Closed** 2023-01-19 23:10 UTC
Labels: duplicate
